# 메인 파일 이름을 지정하세요.
main_file = 'main.py'# fill here

# 데이타 파일들을 지정하세요.
data_files = [
    # fill here
    'animation_sheet.png', 'cock.png',
    'ground.png', 'how_to_play.png', 'net.png', 'stadium.png', 'title.png'
]

# 데이타가 들어있는 폴더들을 지정하세요.
data_folders = [
    # fill here
]

